export const ADD_TO_CART = "ADD_TO_CART";
export const INCREMENT_PRODUCT_QUNATITY = "INCREMENT_PRODUCT_QUNATITY";
export const DELETE_FROM_CART = "DELETE_FROM_CART";
export const SHOW_LOADING = "SHOW_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";
